### ISSUE TITLE
Подключить Bottom Tab Navigator

### ISSUE THREAD

**Issue by Deslifer** [team-dev-spring-2022/teamMPSF#35]
Сейчас Bottom Tab Navigator направляет обратно на Login надо, чтобы он направлял на MainActivity

**Comment by 0pdd** [comment]
@Deslifer the puzzle [#36](https://github.com/team-dev-spring-2022/teamMPSF/issues/36) is still not solved.

**Comment by 0pdd** [comment]
@Deslifer 3 puzzles [#36](https://github.com/team-dev-spring-2022/teamMPSF/issues/36), [#43](https://github.com/team-dev-spring-2022/teamMPSF/issues/43), [#44](https://github.com/team-dev-spring-2022/teamMPSF/issues/44) are still not solved.

**Comment by 0pdd** [comment]
@Deslifer 2 puzzles [#36](https://github.com/team-dev-spring-2022/teamMPSF/issues/36), [#44](https://github.com/team-dev-spring-2022/teamMPSF/issues/44) are still not solved; solved: [#43](https://github.com/team-dev-spring-2022/teamMPSF/issues/43).
