### ISSUE TITLE
Создать страницу входа

### ISSUE THREAD

**Issue by Deslifer** [team-dev-spring-2022/teamMPSF#6]
Сделать по фигме

**Comment by 0pdd** [comment]
@Deslifer the puzzle [#10](https://github.com/team-dev-spring-2022/teamMPSF/issues/10) is still not solved.

**Comment by 0pdd** [comment]
@Deslifer the puzzle [#13](https://github.com/team-dev-spring-2022/teamMPSF/issues/13) is still not solved; solved: [#10](https://github.com/team-dev-spring-2022/teamMPSF/issues/10).

**Comment by 0pdd** [comment]
@Deslifer all 2 puzzles are solved here: [#10](https://github.com/team-dev-spring-2022/teamMPSF/issues/10), [#13](https://github.com/team-dev-spring-2022/teamMPSF/issues/13).
