### ISSUE TITLE
Создать страницу регистрации

### ISSUE THREAD

**Issue by Deslifer** [team-dev-spring-2022/teamMPSF#7]

**Comment by 0pdd** [comment]
@Deslifer 2 puzzles [#17](https://github.com/team-dev-spring-2022/teamMPSF/issues/17), [#18](https://github.com/team-dev-spring-2022/teamMPSF/issues/18) are still not solved.

**Comment by 0pdd** [comment]
@Deslifer the puzzle [#18](https://github.com/team-dev-spring-2022/teamMPSF/issues/18) is still not solved; solved: [#17](https://github.com/team-dev-spring-2022/teamMPSF/issues/17).
